TOP=../..
include $(TOP)/configure/CONFIG
#---------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#=======================================

LIBRARY_IOC_Linux = dectrisCompression
LIBRARY_IOC_Darwin = dectrisCompression

INC += compression.h

LIB_SRCS += 	compression.c

include $(TOP)/configure/RULES
#---------------------------------------
#  ADD RULES AFTER THIS LINE
#=======================================
