TOP=../..
include $(TOP)/configure/CONFIG
#---------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#=======================================

LIBRARY_IOC_Linux = frozen
LIBRARY_IOC_Darwin = frozen
LIBRARY_IOC_solaris = frozen

frozen_SRCS += frozen.c

include $(TOP)/configure/RULES
#---------------------------------------
#  ADD RULES AFTER THIS LINE
#=======================================
