TOP=../..
include $(TOP)/configure/CONFIG
#---------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#=======================================

LIBRARY_IOC = lz4
lz4_SRCS += lz4.c

include $(TOP)/configure/RULES
#---------------------------------------
#  ADD RULES AFTER THIS LINE
#=======================================
